# Generated by Django 5.1.2 on 2024-10-29 20:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="content",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="content",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
